version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: node mintable.js

workflows:
  version: 2

  hourly:
    triggers:
      - schedule:
          # Hourly cron tab at 12:00, 1:00, etc.
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - build
